// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  FORECASTS: SmartBucket;
  logger: Logger;
  LOGS: SmartBucket;
  MAIN_DB: SmartSql;
  mem: KvCache;
  NODE_ENV: string;
  PORT: string;
  RAINDROP_API_KEY: string;
  RAINDROP_MCP_URL: string;
  tracer: Tracer;
  USER_PATTERNS: SmartMemory;
  VULTR_API_KEY: string;
  VULTR_WORKER_URL: string;
}
